export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CABINET_ROUTE = '/cabinet'
export const MEDICAL_ROUTE = '/medical'
export const EVENT_ROUTE = '/events'